### ISSUE TITLE
Patch: Null item appears more than once on postback

### ISSUE THREAD

**Issue by GoogleCodeExporter** [netTiers/netTiers#152]
```
What steps will reproduce the problem?
1. Add EntityDropDownList, enable the null item
2. Postback on a control that isnt the EntityDropDownList
3. Voila!

What is the expected output? What do you see instead?

Expected only one Null Item to appear, two appear etc

What version of .netTiers and CodeSmith are you using?
2.3.0 b1

Please provide any additional information below.

Added a simple "&& !Page.IsPostBack" to the handler for AppendNullItem in 
OnDataBinding


```

Original issue reported on code.google.com by `pzycoman@gmail.com` on 6 Jan 2009 at 11:02

Attachments:
- [EntityDropDownList.cs.cst](https://storage.googleapis.com/google-code-attachments/nettiers/issue-152/comment-0/EntityDropDownList.cs.cst)

**Comment by IorPerry** [comment]
In my code I fixed it in this way:
`if ( AppendNullItem  && base.Items.Count == 0 )`
In this way adds the null item only at begin.

**Comment by niemyjski** [comment]
Nice work around :)
