### ISSUE TITLE
IsPropertyChanged method crashes when I'm creating a new entity

### ISSUE THREAD

**Issue by GoogleCodeExporter** [netTiers/netTiers#217]
```
What steps will reproduce the problem?

Error when _originalData value is null.

What version of .netTiers and CodeSmith are you using?

.netTiers v2.3.0.807

Please provide any additional information below.

I've attached my current template file.


```

Original issue reported on code.google.com by `fvalenzuela.choice` on 26 May 2009 at 11:03

Attachments:
- [EntityInstanceBase.generated.cst](https://storage.googleapis.com/google-code-attachments/nettiers/issue-217/comment-0/EntityInstanceBase.generated.cst)

**Comment by jeremeguenther** [comment]
A fix has been committed for this.  However, in order to use any of the change tracking methods, change tracking must first be initialized, so this code would not have worked anyway.
