### ISSUE TITLE
Lack of Postgres support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [netTiers/netTiers#374]
```
It would be good if .netTiers supported Postgres
```

Original issue reported on code.google.com by `Mark.J.R...@gmail.com` on 17 Feb 2011 at 1:40

**Comment by artasom** [comment]
I know this is an old issue but, was there any patch to add support for Postgres? I tried to use the last version of .netTiers against a Postgres database and I get the error

> Error: This provider is not supported.

Thanks

**Comment by jeremeguenther** [comment]
I have not heard of any.  And unfortunately I am not well versed in Postgres so I could not create one.  If Microsoft's old Enterprise Library 5 supported Postgres then it should be a simple matter of creating sql templates for it, however after a quick search it does not look like it does.

NetTiers claims Enterprise Library is optional, however I have not been able to make it work without it; not that I have tried super hard.  Enterprise Library does need to be designed out of NetTiers, but I think that could be a sizable undertaking.

**Comment by niemyjski** [comment]
it doesn't matter if enterprise library supports it (if I'm remember correctly). There needs to be a db provider / code written to support it. Just search for Oracle on this repo to see how I implemented that.

We really just need to upload a v3 version to a branch. I'll have to dig to see if I still have that some place. It was a WIP if someone wants to take that over.
