### ISSUE TITLE
I am new to .NetTier and i am working with one .NetTier application right now. and i am using codesmith 5.3 eval, how i can write a new stored procedure and how can i map to my code.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [netTiers/netTiers#404]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of .netTiers and CodeSmith are you using?


Please provide any additional information below.

```

Original issue reported on code.google.com by `ved...@gmail.com` on 17 Nov 2011 at 7:03

**Comment by jeremeguenther** [comment]
This is a really old question.  So I will answer it and close it out.  Feel free to open a new issue if you need.

In the .netTiers configuration is an option "CustomProcedureStartsWith".  Choose some prefix, or none at all, and conform your custom stored procedures to that pattern.

I use up_{0}_
This means that my procedure names will be up_TableName_GeneratedMethodName
So the {0} is a place holder that .netTiers uses to figure out which generated service object it should put the new method on, and the last part will end up becoming the name of the method that calls that stored procedure.

If for some reason you are not generating code for all your tables in your database, then you do have to remember that custom stored procedures will only be picked up if their name maps to one of the tables you are generating for.
