### ISSUE TITLE
doubt in procedure prefix and custom storepd procedure

### ISSUE THREAD

**Issue by GoogleCodeExporter** [netTiers/netTiers#426]
```
Hi,

I'm new in NetTiers 2.3.1 . i'ved given the procedure prefix as "usp" and 
custom procedure starts with {1}_{0}_.



While compliing the solution i'm getting the error as some of the fucntion are 
not genereated in the class (*basegenerated.cs).  Please do help me .  
```

Original issue reported on code.google.com by `sabithad...@gmail.com` on 11 Sep 2012 at 9:47

**Comment by jeremeguenther** [comment]
The ProcedurePrefix setting dictates a common prefix that will be used for the .netTiers auto generated procedures.  It should be different from the prefix you use to identify the custom procedures you manually write.

CustomProceduresStartsWith indicates a prefix naming convention that you have used when creating stored procedures in your application.  It only takes one replacement variable, it looks like you are trying to use two replacement variables.  That replacement variable indicates where in the pattern you are putting the name of the table that you would like the custom procedure to be associated with when the CRUD functions are generated.

for example, I use:
ProcedurePrefix = net_ (which means all my .netTiers generated procedures get prefixed with net_ so they are easy to find in the database)
CustomProcedureStartsWith = up_{0}_ (which means all my custom procedures follow the naming convention up_TableName_FunctionDescription)

In your case, it looks like you use usp as your custom procedure naming convention, so try something like this:
ProcedurePrefix = net_
CustomProcedureStartsWith = usp{0}
