### ISSUE TITLE
{"The type ExceptionPolicyImpl has multiple constructors of length 2. Unable to disambiguate."}

### ISSUE THREAD

**Issue by GoogleCodeExporter** [netTiers/netTiers#427]
```
What steps will reproduce the problem?
1. When i click the Event log anf activity log in the administration screen of 
my application I'm getting the issue with the inner exception as {"The type 
ExceptionPolicyImpl has multiple constructors of length 2. Unable to 
disambiguate."}

Exception getting is as follows: 
"Activation error occured while trying to get instance of type 
ExceptionPolicyImpl, key "ServiceLayerExceptionPolicy"".

What is the expected output? What do you see instead?


What version of .netTiers and CodeSmith are you using?
net tiers 2.3.1 and codesmith 6.5 


Please provide any additional information below.

```

Original issue reported on code.google.com by `sabithad...@gmail.com` on 18 Sep 2012 at 7:38

**Comment by kiquenet** [comment]
I was trying configure _Ent Lib 4.1_ for a *Old app .net 3.5 clr 2.0 appPool* and _Ent Lib 5.0_ for a *New app .net 4.5 clr 4.0 appPool* with BOTH configuration files (web.config) , and I get the same error.

**Comment by niemyjski** [comment]
Have you checked to ensure your web.config is valid. Also I'd take a look at the inner exception to see if it provides any more info. I also came across this: http://code.colostate.edu/entlib-in-nettiers.aspx

**Comment by ethar1** [comment]
niemyjski , Could you please help!
I got same error, http://code.colostate.edu/entlib-in-nettiers.aspxnot valid any more.
