### ISSUE TITLE
Buid .netTiers target Framework 4 Client Profile Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [netTiers/netTiers#438]
```
What steps will reproduce the problem?
1. Target Project to Framework 4 Client Profile
2. Build
3. Display Error "Microsoft.Practices.EnterpriseLibrary.Data;"


```

Original issue reported on code.google.com by `tuanpms...@gmail.com` on 4 Aug 2014 at 3:52

**Comment by jeremeguenther** [comment]
This sounds like an issue where someone chose the wrong version of Enterprise library for the version of .net they generated for. Hard to diagnose with so little information though.
