### ISSUE TITLE
Documentation for TransactionManager

### ISSUE THREAD

**Issue by divmgl** [netTiers/netTiers#445]
I have looked through all of the documentation and I cannot find information regarding the `TransactionManager`, which is heavily used in a project I'm working on. Does the netTiers team have plans to improve the documentation?

**Comment by niemyjski** [comment]
I've went a head and updated all of the documentation recently (pulled it from the old wiki). I have no plans to update the documentation any further than it is until more feature work/bug fixes is done. If you could add documentation/submit a pull request for this that would be a great help.

**Comment by niemyjski** [comment]
We are looking for people to help out with this project.

**Comment by divmgl** [comment]
I have never worked with netTiers nor do I plan on becoming well-versed in it... However, if there are any improvements I can make to netTiers I'll open a pull request. I'm going to keep this issue open until we've added documentation for `TransactionManager`
