### ISSUE TITLE
Exception difference between deployments

### ISSUE THREAD

**Issue by tariqalardah** [netTiers/netTiers#446]
#Question:
I have problem that I cannot fix, I have table with unique index, while trying to save a big list at once, sometimes i got SqlException of "cannot insert duplicate key".
The problem is that it contains what was this key value in my local machine, but does not in deployment server! although i am using same DLLs including same Enterprise Library DLLs!

__Local sample:__
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Cannot insert duplicate key row in object 'dbo.ActivityBySource' with unique index 'IXU_ActivityBySource_Code'. The statement has been terminated.

__Deployment Server Sample:__
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Cannot insert duplicate key row in object 'dbo.ActivityBySource' with unique index 'IXU_ActivityBySource_Code'. **The duplicate key value is (2412-7521-004).** The statement has been terminated.

Any Ideas please?

**Comment by tariqalardah** [comment]
sorry, deleting the issue as it is related to sql server version!

**Comment by niemyjski** [comment]
Thanks for the update
