### ISSUE TITLE
NetTiers Default maximum rows 

### ISSUE THREAD

**Issue by VedavathiB** [netTiers/netTiers#447]
Hi,
In NetTiers generated DataAcess Layer entities, while creating stored procedure the "Default Maximum rows" set to 10000, whereas our data has exceeded beyond 10000 and we are facing functionality being broken.
Can you please help us to overcome this situation.
Please dont advice to increase to more than 10000, for ex:20000. please suggest the permanent fix

**Comment by niemyjski** [comment]
You can change the stored procedure / update the template or for the love of god use paging (perminate fix)!!!!!
