### ISSUE TITLE
DeepSave children order

### ISSUE THREAD

**Issue by IorPerry** [netTiers/netTiers#448]
Good morning,
I have a 3 tables "Buildings", "Analysis" and "Adjustment", because of the foreign keys I need they are save in this order:Buildings,  Analysis and then Adjustment. I do a deepSave on BuildingsService in this way:
`bldProvider.DeepSave(newbuilding,DeepSaveType.IncludeChildren,new System.Type[] { typeof(TList<Analysis>), typeof(TList<Adjustment>) });`  (in the original code the list is dynamic but Adjustment is always after Analysis)
But in the generated code does not take into account the order in children list (in the **EntityProviderBaseCore.generated.cst** file).
Do I must do a hand-code deep save?
I think if you substitute the  Dictionary<string, KeyValuePair<Delegate, object>> with an array (the key is not used) and put the values the same order of childTypes my problem will solved.

Thanks,
Antonino

**Comment by niemyjski** [comment]
I'm not sure, I'd recommend debugging and stepping through it and see how the order you added the items affect the save order. Like you said, you might need to override deep save.

**Comment by IorPerry** [comment]
Thank you for response, I changed my code in this way:
`var tran = DataRepository.Provider.CreateTransaction();`
`tran.BeginTransaction();`
`try {`
`bldProvider.DeepSave(tran,newbuilding,DeepSaveType.IncludeChildren,new System.Type[] { typeof(TList<Analysis>) });`
`bldProvider.DeepSave(tran,newbuilding,DeepSaveType.IncludeChildren,new System.Type[] { typeof(TList<Adjustment>) });`
`tran.Commit();`
`} catch(Exception){`
`tran.Rollback();`
`throw;`
`}`
And it works.
I think the tables are added in alphabetic order.

**Comment by niemyjski** [comment]
Awesome!
