### ISSUE TITLE
Can I reverse the process and generate the configuration/templates used to create my nettiers layers by looking at existing layers

### ISSUE THREAD

**Issue by seanhrt** [netTiers/netTiers#451]
Hi - I have recently taken over support/development of a web site project that relies on dlls generated in nettiers.  I of course need to update the database, adding tables, changing tables, etc, and then regenerate the nettiers dlls.  I do not have any access to original developers to ask questions.  How can I generate the configuration that was used to generate my existing nettiers dlls, so that when I regenerate my results match to what we have currently?

Does this make sense?   If I can't do this I am then stuck in a bit of a guessing/trial and error game to play with the configuration until my output matches my current dlls.

Any thoughts, tips, etc would be a huge help.  I have 15 years .NET experience, but am brand new to nettiers and codeplex.

Thanks!!

**Comment by niemyjski** [comment]
Trial an error is really the only way, that's why the .csp (with all the settings) file should be checked into source control. Chances are it's a default config.

**Comment by seanhrt** [comment]
That is what I was afraid of.....but thanks for the quick response.

Sean
