### ISSUE TITLE
How do I generate filter and query files in my data layer

### ISSUE THREAD

**Issue by seanhrt** [netTiers/netTiers#453]
I am working on replicating nettier layers to match what was previously generated.  I do not have the original template so working from scratch.  In the Data tier i have currently that I am attempting to regenerate, I see a number of files that correspond to the my base,  bu these do not get generated when I attempt to recreate them.  Examples:

I have a base file:
coutryproviderbase

along with this I also see these addtional files:
countryfilterbuiilder
countryparameterbuilder
countryproviderbasecore
countrysortbuilder
CountryFileter
CountryQuery

When I regenerate the only file I get is the base:
coutryproviderbase

What settings am I missing in my configuration when regenerating?   Thanks!  Sorry I am totally new to this nettiers app and struggling to get familiar with all of its settings.   I need to be able to regenerate so that I can continue to develop my database and regenerate these layers as I move forward.

I appreciate any help, tips, pointers to good documentation.

Thanks!!

Sean

**Comment by niemyjski** [comment]
From the looks of it, that should be generated if you are generating the. data access layer and or enterprise library (https://github.com/netTiers/netTiers/blob/8ac2d500a4d35b4610a0fb47b2870b8f7e65aac4/Source/NetTiers.cst) You'll need to take a look through the source by searching for the class you are looking for and then look at the conditions inside of the template.
