### ISSUE TITLE
using the IEditableObject.BeginEdit feature

### ISSUE THREAD

**Issue by jeremeguenther** [netTiers/netTiers#461]
I have noticed in my implementation of NetTiers that none of the data changed methods work because no data changes are actually being tracked.

Digging into this Nettiers generates a method on every object called IEditableObject.BeginEdit().  From reading online it looks like this is supposed to be a public method that is then called manually in code.  Another option might be to put it into the set method on all the Properties.

My questions are: is this a finished feature, if so, how do I use it?  If not, then what would be a good approach for finishing it?

**Comment by jeremeguenther** [comment]
I think I answered my own question.  It probably is a complete feature, and can be activated manually in the following way:

                    var casted_obj = (System.ComponentModel.IEditableObject)nettiers_generated_obj;
                    casted_obj.BeginEdit();

**Comment by niemyjski** [comment]
@jeremeguenther would you like commit access and help maintain this project?

**Comment by jeremeguenther** [comment]
I would love that.

Is there any kind of review process in place?  I have appreciated the
second set of eyes on my changes before each merge so far.

--
Jereme Guenther, MCP
LinkedIn <http://www.linkedin.com/in/jeremeguenther>

**Comment by niemyjski** [comment]
I've added you. I'd just do the work in branches so master is always stable (git flow if possible) and do pr's for all changes. If you want just add me as a reviewer  (I can see if I can do that by default). I kinda always tried keep it simple and try to make sure changes don't make us compromise later :)

**Comment by jeremeguenther** [comment]
Sounds like a plan.  I will try and remember to do that the next time I
have something to contribute.

--
Jereme Guenther, MCP
LinkedIn <http://www.linkedin.com/in/jeremeguenther>
