### ISSUE TITLE
Provider error

### ISSUE THREAD

**Issue by jasona22** [netTiers/netTiers#464]
I am afraid I am in the wrong place, sorry if thats the case.  I am new to netTiers and I'm having a great deal of difficulty.

I first downloaded 2.3.2.  I pointed it at WildWorldImporters (or whatever the new SQL Server sample database is called) and had like 375 compile errors.  I kind of thought it would just work as a first example.

I then created my own database, put a table in it.  Turned off the web stuff (I know nothing about web development) and hoped to just build a library of my business object.  It did that.  Actually, it build lots of stuff.  Kind of overwhelming really.  There was a lot.  Anyhow, I took the report that is generated and from what I could tell I was to use the Provider it gave me in my config.  Fumbled around in there a bit and got mine looking like I thought it should.  

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section  name="Sample.Data"
              type="Sample.Data.Bases.NetTiersServiceSection, Sample.Data"
              allowDefinition="MachineToApplication"
              restartOnExternalChanges="true" />
  </configSections>

  <connectionStrings>
    <add name="netTiersConnectionString" connectionString="Data Source=.;Initial Catalog=Sample;Integrated Security=True" />
  </connectionStrings>

  <Sample.Data defaultProvider="SqlNetTiersProvider">
    <providers>

      <add
    name="SqlNetTiersProvider"
    type="Sample.Data.SqlClient.SqlNetTiersProvider, Sample.Data.SqlClient"
    connectionStringName="netTiersConnectionString"
    providerInvariantName="System.Data.SqlClient"
    entityFactoryType="Sample.Entities.EntityFactory"
    useEntityFactory="true"
    enableEntityTracking="false"
    enableMethodAuthorization="false"
    useStoredProcedure="false"
  />

    </providers>
  </Sample.Data> 
</configuration>

Problem is, when I try to save my object, I get a provider error that points to System.Web.dll that it couldn't load file or assembly "Sample.Data.SQLClient" or one of its dependencies.  Since I turned off web, I am thinking that reference to system.web is wrong.  

Sadly, the years of using being pigeonholed into CodeSmith templates and library generation in a CSLA environment has made me dumb to pretty much everything else (like using cell phones make us not need to know phone numbers and calculators remove the need for most math).  I do not know the technologies and patterns and the like that I am generating and thus do not really know how to use them.  Is there a for dummies guide?  Of course, this team is opposed to CSLA or I'd be rocking.

Anyhow, enough whining, I just need a library of objects that the UI developers will do WPF magic and bind up some view modles and xaml stuff (not my domain either) against a SQL database.  No web.

Of course, I am not sure there isn't some bug somewhere (note not compiling after SQL Sample DB (current version) and the web.dll reference that doesn't make sense).

Any guidance would be helpful.

Jason

**Comment by jasona22** [comment]
lets try a file instead.  I don't think the config looks right in the above.


[App - Copy.config.txt](https://github.com/netTiers/netTiers/files/2285102/App.-.Copy.config.txt)

**Comment by jeremeguenther** [comment]
Try compiling your dlls individually.
It sounds like you will just need the 4 core dlls:
Namespace.Data
Namespace.Data.SqlClient
Namespace.Entity
Namespace.Service

If those will compile for you, then we can work on the config and you can use just those 4 dlls as the data access layer.  I'm not sure how many people actually use the web layer at the moment.  And I know the Soap service layer no longer functions correctly.

Code tends to only be kept up to date in areas that people are using.

**Comment by jeremeguenther** [comment]
Actually, it sounds like you are compiling.  I might need the cs code you are getting errors when using.

**Comment by jeremeguenther** [comment]
Providers are used when you want the option of being able to swap out connection strings at run time.  A simple Service can be used if you do not need that capability.  I am sure purists will say to always use Providers, but I use the Services directly heavily.

I am not familiar with CSLA.net, so I am not sure how it compares to NetTiers.  NetTiers shines as an auto generated Data Access Layer, with a couple extra minor features bolted on.

Without seeing more code.  Your specific error kind of sounds like you are referencing a dll that does not exist.  That could very well be an error in the template system.  There are so many options in NetTiers that various bugs exist based on the feature combination you choose to use.  Try manually removing all nettiers dlls except for the 4 core ones, and the enterprise library ones.

I'm trying to do about 10 things at once here, so sorry if my responses are a bit all over the board.

**Comment by jasona22** [comment]
OH!  Sorry, I'm stupid... said that I think...   I added the references, but one of the little reference check box didn't actually check, so only 3 of the 4 was in there.  The SQLClient one was missing and thus the error.  I was just confounded by the web.dll error and got wrapped around the axle there.

So, while talking, when I generate for 1 table, I get like 59 objects.  I am hoping most of that is just helper classes and interfaces and I will basically just be using my table objects and not directly needing EntityBase, Cache, Factory, et al.

And what code goes in App_Code?

Sorry, I'm excited that my save button pushed something to the database, now I want to know the other stuff and set it up well.  Surely hate to open the doors to the view model guys and then find out I should have set it up in a really different way.

Thanks a ton for your prompt responses

**Comment by jeremeguenther** [comment]
If you want the get and save functionality then you are stuck with all the objects and all 4 of those DLLs.
If for some odd reason you were going to create your own get and save methods I suppose you could just keep the Entity DLL.

Nothing goes in App_Code, I'm not even sure if that is used anymore in MVC.
Originally when NetTiers was developed it was designed to generate code directly into your project. And there were visions of generating all sorts of things like an admin interface for your site.

I personally generate to a separate folder, then just copy in the code for the three core DLLs that I use.  I would recommend you do the same.

You will get one object for every table, and view, along with provider objects and services objects for each.
Most of the time you will use either a Provider or a Service to get/save a table/view object.  That's about it. I think it would be pretty hard to get rid of the EntityBase, or Factory.  Some of the caching you should be able to turn off and I suppose you could manually delete the Cache object; careful though, because it is still used by the Factory if I remember right.

I would just recommend you keep all the objects.  I think eventually you will find you like most of them. .generated.cs files were created so that you could write custom code into the main.cs file and it would not get overwritten when generating the files.  I prefer to write extension methods myself, but it is your choice.

**Comment by jasona22** [comment]
I was not clear in  my point.  I don't want to rid of any of the objects
(admittedly there are a LOT of them).  I was more interested if I have to
directly interact or if they are just helpers to support the actual
business object operations.

I think, based on your "just copy the dlls" part, that the consumers (UI
developers) will just add references and consume the objects directly.

I think I have just one more question at the moment.  Where is the mapping
of the data from the database to the business object?  Is this handled via
generation or is that a manual thing?  In CSLA, we have a partial class
BusinessObject.DataAccess.vb (or .cs) that is similar to what you have in
netTiers for businessObject.generated.cs,and has all the CRUD stuff and a
mapper that maps the various properties to the business object after
fetching data.  Basically, our DAL is called to retrieve the data and
returns a DataReader to the business object which has a mapping function.
We also have lots of partial methods for hooking various parts in the event
of customization.  I should probably just package up a business object from
my other project and give it to you.  It has some cool techniques for
easily hooking into stuff (OnCreating and OnCreated, and the like.). So if
you had a custom stored proc that returned extra data, you could hook the
OnMapping via a partial method to the "generate once" code
(businessObject.vb) and set your custom property values and return
execution back to the generated mapper to complete its mapping

Anyhow, I truly appreciate the time you've spent with me.  I really
appreciate it a lot.

Jason

**Comment by jeremeguenther** [comment]
Yes, UI developers should only need to reference the Entity namespace and use those objects.

There is no dynamic or on the fly creation of properties in NetTiers.  The CRUD methods are generated off of meta data from the database, so any data base changes require a re-run of NetTiers.

The SqlClient dll is the one that actually calls the database returning readers that it uses to fill object and object lists.

The Service dll wraps the SqlClient dll providing additional functionality such as caching, security, and deep load capabilities.

The Entity dll is nothing more than a static creation of the objects themselves based on database tables and views.

The Data dll is a location for misc helper type stuff like filter builders for parameterized sql queries, and the provider capabilities.

For the most part you will interact with the Entity objects and the Service objects, unless you choose to use Providers instead, then you will use the Data dll more.

For basic usage you need the Entity objects/dll and a CRUD layer, choose either the Service or the Provider (data dll) CRUD layer.

The SqlClient dll has the ability to raise events like OnDataRequesting, OnDataRequested.  The Entity dll has events like OnPropertyChanging, OnColumnChanging, OnColumnChanged, OnPropertyChanged.  However, I have only been using NetTiers for 3 years now and have not had the need to use any of those, so they are a bit outside of my expertise area.

Custom stored sprocs in NetTiers ( as long as they follow the naming convention ) get their own methods generated so they are easy to access.  They can return either DataSets or Entity object lists depending on how they are named and the fields they return.

**Comment by jasona22** [comment]
Great info.  Thanks.

In my current project, I have an area where a developer can add a property
with the afore mentioned hooks for mapping data from the reader into the
property.  I've found that not all business objects map 1:1 with the
table.  Sometimes, the data you need to present or edit might require a
join between multiple tables and thus you would need to extend your object
with properties beyond those defined on just one table (think normalized
personnel data (name, address and the like)  A normalized address could be
several tables worth of data if done properly.  So to present a screen for
editing a user you might need a query to return a result set quite a bit
different than just the Personnel table that might have (FName, LName, SSN,
DOB) type data.  Is this a possibility within the current generation?
Custom Stored Procs for insert, update and select?

**Comment by jeremeguenther** [comment]
Typically the functionality you are seeking would be accomplished using:
1 - a custom sproc, eg:
up_TableName_CustomSprocName (where up_ is the prefix you configured in nettiers for custom sprocs, TableName is the name of the Table/Service you want the method generated on, and the rest is the name of the sproc/method generated.)
As an aside, if you return all the columns from the table TableName, then the sproc will return a list of objects rather than a dataset.

2 - a view
From which you would then generate a parameterized sql query to get the denormalized records you want back.

3 - deep load
Using the deep load capabilities you can load multiple objects into memory based on foreign key relationships.  Care must be taken here because a separate Get call is generated to the database for every object that the deep load is required to get.  However, at times it is a very powerful tool.

The deep load option is the only one that would allow you to save the data back to the database using the objects that were loaded.  For views or custom sprocs you would have to copy the data onto an Entity object and save it that way ( It's best to get the object from the database first and just change attributes in this case ).

**Comment by jasona22** [comment]
quick question regarding netTiers.cst.

So I pulled the framework down.  I open the nettiers.cst and update all the
properties the way I want.  I save it.  I generate it.  Volia, things
working.... great.

HOWEVER!  The next time I  open the netTiers.cst, all the settings are
gone!  I don't want to have to remember what is set what way (thats a long
list of properties).  When my schema changes, I'd like to open netTiers.cst
and press generate.  That is, at least as I have experienced in the CSLA
version of frameworks, how it seems it should be.  What am I doing wrong
regarding saving the values?

Thanks

Jason

**Comment by jeremeguenther** [comment]
You should never be touching the .cst file at all, unless you are working on making changes to NetTiers.

The NetTiers.csp file is the project file.  That will open up in Code Smith's little generator program, you can edit the settings using that GUI.  Those settings will remain saved in the .csp file.

**Comment by jasona22** [comment]
ah, found it.  After generation, it dumped the .csp in a folder in my
project.  I was at the original netiers framework download.  Missed that!

Thanks for rapid response.

J

**Comment by jasona22** [comment]
I am sorry for bugging you.

I have an interesting problem.  First important part is I have modified the
template to generate my OrganizationBase.Generated.cs base constructor to
initialize my Id field with a valid guid. added a line that looks like
this: this.EntityId.Id = Guid.NewGuid();  For giggles in debugging, I added
a this.Id = Guid.NewGuid(); as well, but no behavior change has been seen.

In the code behind (team I am working with doesn't use MVVM), I have code
like below.  (technically, the ModelList and Model are properties that are
associated with Dependency properties)  The use case is I have a screen to
create organizations in my system.  There are 2 problems here, but I think
one will solve the other -- maybe.


Dim ModelList as TList(Of Organization)
Dim Model as Organization

Model = ModelList.AddNew()

Model and ModelList have an entry where the Id field is all zeros (empty
guid).  Thing is, when I step into the AddNew, I see it go through my
constructor and get added to the list with a guid in it.  Moreover, if when
I step back out of the business object, but before I step off the setter,
the Model is still null (nothing in vb speak) and the ModelList has an item
in it with a guid.  It isn't until I set the Model (step off that line and
to the next line) that the Id's go to zeros.

One other note, when doing the popup to look at the values of the object at
a break point, the EntityId is populated and Id is all zeros.  This hasn't
changed regardless of whether the extra this.Id = Guid.NewGuid();

Any ideas?  Is there a better way to initialize my Id field in the business
object?  For us, there is no need to have a blank one and have to set it on
the UI side; seems silly really.  Get a new object with housekeeping fields
pre-set.

Thanks in advance.


PS: a peek into problem 2 is that
ModelList.CancelNew(ModelList.IndexOf(Model)) doesn't actually cancel the
edit.   So if I add a new Model to my ModelList and then the user cancels
via cancel button, calling CancelNew doesn't do anything.  The object is in
there, flagged as new and valid.  The code doesn't error.  But it doesn't
remove the "isnew" item from the list either.

Thanks again.

**Comment by jeremeguenther** [comment]
Don't modify the templates. If you are trying to change templates to things specific to you, then contact Code Smith for support, at that point you are no longer using nettiers.

If you are just looking to use a guid as your primary key. Then try setting the default value in the database, then turn on the nettiers ability to have all objects initialized to the defaults they have in the database. I'm not sure if it supports new guids or not.

If that doesn't work. Then create an extension method for initialising your object. Or create a new object and inherit the nettiers one and set your defaults on creation. Or modify the OrganizationBase.cs file directly, not the template and not the .generated.cs file, that is the original purpose of that file, and set your defaults there.

**Comment by jeremeguenther** [comment]
Changing the templates is fine. You are just leaving nettiers behind at that point so this is no longer the forum to get support in.

If you can create a new object stand alone and your guid modification works, then there is a possibility of a big in the addnew method. If however your guid is still missing then it sounds like the template modification was not done in the correct place.

Either way, it is not a change currently supported by nettiers.  This or any of the other suggestions you have for nettiers would be great if you wanted to fix issues or implement changes, and submit working tested pull requests for them.

Currently most nettiers changes only happen if a user of nettiers learns it really well, and has personal need of a change and they are then willing to submit it as a pull request for community review and acceptance.
