### ISSUE TITLE
Generating dal with nettiers template

### ISSUE THREAD

**Issue by ang-bain** [netTiers/netTiers#465]
Hi , i have got stuck on this error and not sure how to proceed. It seems to be having a problem with the foreign key...but the key is not new 
Error	CS0029	Cannot implicitly convert type 'vlsNET.BLL.TList<vlsNET.BLL.UserDetails>' to 'vlsNET.BLL.UserDetails'	vlsNET.DAL

the method on the offending line is - 	

public override vlsNET.BLL.UserDetails Get(TransactionManager transactionManager, vlsNET.BLL.UserDetailsKey key, int start, int pageLength)
		{
			return GetById(transactionManager, key.Id, start, pageLength);
		}
		

I really need this working asap so any help or direction would be appreciated..

**Comment by jeremeguenther** [comment]
It would be helpful to have the code that is calling into this method.

The method indicated looks like the one generated for the primary key on a table.  As far as I know, the primary key always generates a method that returns a single object rather than a list.  In speculation here, is it possible that you used to have a custom sproc
up_UserDetails_Get
That would generate an overload that returned a list of objects rather than a single object?

**Comment by ang-bain** [comment]
Yes it generates the files directly into the project..I can only build the bll project seperately at the minute

**Comment by jeremeguenther** [comment]
As long as you can build the nettiers dlls separately successfully then that means the templates and generation are most likely good.  Which goes back to my custom sproc theory.

Could you paste in the line of code from your project that calls into the nettiers data access layer?  The line that is blowing up.

**Comment by jeremeguenther** [comment]
Unless by dll you are referring to some dll other than nettiers.

**Comment by ang-bain** [comment]
Hi, I can only build one out of 4 separately..I just noticed that on the template within the crud section there is a param called includegetlistbyfk. i don't know if this is usually on or off but as its choking on the foreign keys for that table i'll try taking that off and generating again to see what happens

**Comment by ang-bain** [comment]
ok made some progress with that..ie managed to build 3 out of 4 projects. now getting error 

	'ILinkedDataSource' does not contain a definition for 'DeepLoad' and no accessible extension method 'DeepLoad' accepting a first argument of type 'ILinkedDataSource' could be found (are you missing a using directive or an assembly reference?)	vlsNET.Web	C:\source\repos\NDAVLSrepository\VLSDev\vlsNET\vlsNET.Web\Data\EntityRelationshipMember.cs	354	N/A

**Comment by jeremeguenther** [comment]
Are you missing tables in the list of source tables?

I would suggest trying to do a clean generation of nettiers either into a separate project, or first copy out your existing code, then delete your entire nettiers layer and re-generate it.  If you rename tables, or delete tables, the generated code files for them do not automatically get deleted.  That accidentally removing tables from the source list are the two things I have most often run into that cause errors in the nettiers build itself.

**Comment by ang-bain** [comment]
I have been doing that each time jereme..i delete everything in the project folder...i'll try again though..all tables are selected..have you ever come accross this 'ILinkedDataSource' issue

**Comment by jeremeguenther** [comment]
No, I have not seen the ILinkedDataSource error, however, you are using the Web project.
I only use the .Data, .Data.SqlClient, .Entity, .Service projects.  See if those 4 projects will build for you.

**Comment by jeremeguenther** [comment]
You mentioned that 3 out of 4 projects built for you, but you are using the .Web project.  So I am wondering if perhaps you are missing one of the 4 core projects?  I would expect you to have 5 nettiers projects when .Web is included.

**Comment by ang-bain** [comment]
mmm.still the .web sticking on this ilinkeddatasource error..as long as i have been working with this application there have always been the 4 projects. bll, dal, dal.sqlclient and web

**Comment by jeremeguenther** [comment]
When was the last time you updated your nettiers templates?

I have been using it for about 4 years now.  And in that time it has had these default names.

the 4 core dlls
<customname>.Data
<customname>.Data.SqlClient
<customname>.Entity
<customname>.Service (looks optional, but i've always used it)

optional folders for other features
<customname>.SQL
<customname>.UnitTest
<customname>.Web
<customname>.Website

Is it possible that someone customized all your dlls? so
bll = Entity
dal = Data
dal.sqlclient = Data.SqlClient

I just verified that nettiers still builds if I remove my optional .Service dll.  Which probably means that your 3 core nettiers dlls are working.

So the next question is, do you actually use the .Web layer for anything, or can you remove it?  As far as I know it is pretty outdated.

**Comment by jeremeguenther** [comment]
outdated does not mean non-functional.  It has simply not kept pace with more modern grid type controls that are coming on the market.

**Comment by ang-bain** [comment]
thats..what im having a look at now.. :) to see if the web one is actually needed

**Comment by ang-bain** [comment]
Hi jereme..i can't see that leaving the web project out will cause me any problems however..i'm having a lot of problems as a result of taking out the foreign key selection parameter from the dal project. Although the dal project built when i removed this, the main application is throwing - 'GetById' is not a member of 'vlsNET.DAL.Bases.CourseUsersProviderBase' all over the place on different ProviderBase pages. So i need to find what is going wrong with the template and generator.

**Comment by ang-bain** [comment]
its my primary key it seems to be getting stuck on :( see below ...not sure where to go from here
		
#region Get By Index Functions
		
		/// <summary>
		/// 	Gets a row from the DataSource based on its primary key.
		/// </summary>
		/// <param name="transactionManager">A <see cref="TransactionManager"/> object.</param>
		/// <param name="key">The unique identifier of the row to retrieve.</param>
		/// <param name="start">Row number at which to start reading, the first row is 0.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <returns>Returns an instance of the Entity class.</returns>

		public override vlsNET.BLL.UserDetails Get(TransactionManager transactionManager, 
                        vlsNET.BLL.UserDetailsKey key, int start, int pageLength)
		{
			return GetById(transactionManager, key.Id, start, pageLength);
		}

**Comment by niemyjski** [comment]
Can you please provide a simple sql script to create the table (minus any extra columns) in question.

**Comment by ang-bain** [comment]
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[user_details](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[regdate] [datetime] NULL,
	[name] [varchar](255) NOT NULL,
	[password] [varchar](32) NOT NULL,
	[email] [varchar](255) NULL,
	[role] [varchar](255) NOT NULL,
	[access] [int] NOT NULL,
	[tutor] [varchar](1) NOT NULL,
	[last_logged_in] [datetime] NULL,
	[title] [varchar](255) NOT NULL,
	[firstname] [varchar](255) NULL,
	[middlename] [varchar](255) NULL,
	[surname] [varchar](255) NOT NULL,
	[tel] [varchar](255) NULL,
	[firstlogin] [smallint] NOT NULL,
	[profile] [varchar](max) NULL,
	[IsDeleted] [bit] NOT NULL,
	[IsDeletedDate] [datetime] NULL,
	[IsDeletedBy] [bit] NULL,
	[Course] [int] NULL,
	[VLSMailRevealSender] [bit] NULL,
	[isStudentSupport] [bit] NULL,
	[isMailAllStudentsAllCourses] [bit] NULL,
	[isDuplicate] [bit] NULL,
	[isDuplicateDate] [datetime] NULL,
	[isMailUserDefinedCourses] [bit] NULL,
	[FormativeExistsForStudent] [bit] NULL,
	[isHistoricDate] [datetime] NULL,
	[fromDiploma] [bit] NULL,
	[fromDegree] [bit] NULL,
	[fromBA] [bit] NULL,
	[fromMA] [bit] NULL,
	[isEC] [bit] NULL,
	[Level23Decision] [bit] NULL,
	[Level23DecisionMailSentForModID] [int] NULL,
	[isProProfsRegistered] [bit] NULL,
	[StudType_ID] [int] NULL,
 CONSTRAINT [PK_user] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[user_details] ADD  CONSTRAINT [DF__user__role__33D4B598]  DEFAULT ('none') FOR [role]
GO

ALTER TABLE [dbo].[user_details] ADD  CONSTRAINT [DF__user__access__34C8D9D1]  DEFAULT ((1)) FOR [access]
GO

ALTER TABLE [dbo].[user_details] ADD  CONSTRAINT [DF__user__tutor__35BCFE0A]  DEFAULT ('0') FOR [tutor]
GO

ALTER TABLE [dbo].[user_details] ADD  CONSTRAINT [DF__user_deta__first__2B0A656D]  DEFAULT ((0)) FOR [firstlogin]
GO

ALTER TABLE [dbo].[user_details] ADD  CONSTRAINT [DF_user_details_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO

**Comment by ang-bain** [comment]
thanks for having a look :)

**Comment by jeremeguenther** [comment]
Have you tried generating nettiers to a completely separate folder, and opening and building the DAL.sln file it generates?
I just tried that with the table you provided and it compiled perfectly for me.
I did have to remove the TEXTIMAGE_ON flag you had on the table to get it to create though.

**Comment by ang-bain** [comment]
i'll try now..

**Comment by ang-bain** [comment]
If I build the solution i get 18 errors
If i build the bll project (i usually build this first) I get 5 errors

Error	CS0102	The type 'IEntity' already contains a definition for 'IsDeleted'	vlsNET.BLL	C:\source\repos\NDAVLSrepository\VLSDev\testtiers\vlsNET.BLL\IEntity.cs	
Error	CS0102	The type 'EntityBaseCore' already contains a definition for 'IsDeleted'	vlsNET.BLL	C:\source\repos\NDAVLSrepository\VLSDev\testtiers\vlsNET.BLL\EntityBaseCore.generated.cs	274	N/A
Error CS0546	'UserDetailsBase.IsDeleted.set': cannot override because 'EntityBaseCore.IsDeleted' does not have an overridable set accessor vlsNET.BLL	C:\source\repos\NDAVLSrepository\VLSDev\testtiers\vlsNET.BLL\UserDetailsBase.generated.cs	911	
Erro rCS0534	'UserDetails' does not implement inherited abstract member 'EntityBaseCore.IsDeleted.set'	vlsNET.BLL	C:\source\repos\NDAVLSrepository\VLSDev\testtiers\vlsNET.BLL\UserDetails.cs	17	N/A
Error	CS0534	'UserDetails' does not implement inherited abstract member 'EntityBaseCore.IsDeleted.get' vlsNET.BLL	C:\source\repos\NDAVLSrepository\VLSDev\testtiers\vlsNET.BLL\UserDetails.cs

**Comment by ang-bain** [comment]
Yes..that gets rid of the isDeleted errors but still got tis one when try to build dal

Error	CS0029	Cannot implicitly convert type 'vlsNET.BLL.TList<vlsNET.BLL.UserDetails>' to 'vlsNET.BLL.UserDetails'	vlsNET.DAL	C:\source\repos\NDAVLSrepository\VLSDev\testtiers\vlsNET.DAL\Bases\UserDetailsProviderBase.generatedCore.cs	75	N/A

**Comment by jeremeguenther** [comment]
Are you using Microsoft SQL Server, and which version?
Could you upload the vlsNET.DAL\Bases\UserDetailsProviderBase.generatedCore.cs file?

**Comment by jeremeguenther** [comment]
Your nettiers settings are pretty different from mine, especially since you are not using the most current version.

I tried switching my template to generate for .net 4 and visual studio 2010, which seemed to be the most glaring differences.  But I still got a good generation that compiled.

**Comment by ang-bain** [comment]
[Bases.zip](https://github.com/netTiers/netTiers/files/2442938/Bases.zip)

I thought i was using the latest version..

**Comment by ang-bain** [comment]
i'm just using the one that came with codesmith..is there another one?

**Comment by jeremeguenther** [comment]
The code base on github is the most current.

In your case though, it looks like there a few indexes on the table _dta_....... that are causing your issues.  Particularly an extra index on the Id column in addition to it being the primary key.  Nettiers is trying to generate both the primary key get method and the index get method, the former returns a single object, the later returns a list of objects.

It is definitely a bug in the Nettiers templates.  However, if it is really triggered by a duplicate index then I doubt anyone is going to have the time to fix the issue.  I personally like compile issues like this, helps prevent me from certain mistakes in the database.

**Comment by ang-bain** [comment]
yeah..they were created by the sql tuning wizard...ok i'll try taking off the index and see if i can get it to compile..its interesting though as these have been on there for a while and i've only got this problem now..

**Comment by ang-bain** [comment]
no joy..i'll try downloading the code base and see if i can get that to work after dinner

**Comment by jeremeguenther** [comment]
send over an updated copy of the generated code file as well so I can do a compare against the one I generated.

**Comment by ang-bain** [comment]
Hiya, ok updated to latest code and template..still get this
Error	CS0029	Cannot implicitly convert type 'vlsNET.BLL.TList<vlsNET.BLL.UserDetails>' to 'vlsNET.BLL.UserDetails'	vlsNET.DAL	C:\source\repos\NDAVLSrepository\VLSDev\testtiers\vlsNET.DAL\Bases\UserDetailsProviderBase.generatedCore.cs	
Error	CS0029	Cannot implicitly convert type 'vlsNET.BLL.TList<vlsNET.BLL.UserDetails>' to 'vlsNET.BLL.UserDetails'	vlsNET.DAL	C:\source\repos\NDAVLSrepository\VLSDev\testtiers\vlsNET.DAL\Bases\GlLogProviderBase.generatedCore.cs	
Error	CS0029	Cannot implicitly convert type 'vlsNET.BLL.TList<vlsNET.BLL.UserDetails>' to 'vlsNET.BLL.UserDetails'	vlsNET.DAL	C:\source\repos\NDAVLSrepository\VLSDev\testtiers\vlsNET.DAL\Bases\GlLogProviderBase.generatedCore.cs	
Error	CS0029	Cannot implicitly convert type 'vlsNET.BLL.TList<vlsNET.BLL.UserDetails>' to 'vlsNET.BLL.UserDetails'	vlsNET.DAL	C:\source\repos\NDAVLSrepository\VLSDev\testtiers\vlsNET.DAL\Bases\CdCollegeDataProviderBase.generatedCore.cs	

i'm attaching the generated code files for UserDetailsProviderBase.generatedCore.cs and meanwhile i'll try playing around with the database constraints etc
[Bases.zip](https://github.com/netTiers/netTiers/files/2445913/Bases.zip)

**Comment by jeremeguenther** [comment]
Also, right click on your table in Mangement Studio > Script Table as > Create to > New Query Editor Window.

you gave us the basic table, but in this case it would be nice to have all of the indexes, constraints, and foreign keys that are applied to this table.  All of those will create potentially conflicting methods during nettiers generation.

**Comment by ang-bain** [comment]
Hiya...what ive done up to now

1.created a new skeleton table with the script i sent u yesterday
2. Build with the new nettiers template
3. 4 projects built fine
next step is to add the indexes in one by one to see which one breaks the project..script below for table with constraints

CREATE TABLE [dbo].[user_details](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[regdate] [datetime] NULL,
	[name] [varchar](255) NOT NULL,
	[password] [varchar](32) NOT NULL,
	[email] [varchar](255) NULL,
	[role] [varchar](255) NOT NULL,
	[access] [int] NOT NULL,
	[tutor] [varchar](1) NOT NULL,
	[last_logged_in] [datetime] NULL,
	[title] [varchar](255) NOT NULL,
	[firstname] [varchar](255) NULL,
	[middlename] [varchar](255) NULL,
	[surname] [varchar](255) NOT NULL,
	[tel] [varchar](255) NULL,
	[firstlogin] [smallint] NOT NULL,
	[profile] [varchar](max) NULL,
	[IsDeleted] [bit] NOT NULL,
	[IsDeletedDate] [datetime] NULL,
	[IsDeletedBy] [bit] NULL,
	[Course] [int] NULL,
	[VLSMailRevealSender] [bit] NULL,
	[isStudentSupport] [bit] NULL,
	[isMailAllStudentsAllCourses] [bit] NULL,
	[isDuplicate] [bit] NULL,
	[isDuplicateDate] [datetime] NULL,
	[isMailUserDefinedCourses] [bit] NULL,
	[FormativeExistsForStudent] [bit] NULL,
	[isHistoricDate] [datetime] NULL,
	[fromDiploma] [bit] NULL,
	[fromDegree] [bit] NULL,
	[fromBA] [bit] NULL,
	[fromMA] [bit] NULL,
	[isEC] [bit] NULL,
	[Level23Decision] [bit] NULL,
	[Level23DecisionMailSentForModID] [int] NULL,
	[isProProfsRegistered] [bit] NULL,
	[StudType_ID] [int] NULL,
 CONSTRAINT [PK_user] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[user_details] ADD  CONSTRAINT [DF__user__role__33D4B598]  DEFAULT ('none') FOR [role]
GO

ALTER TABLE [dbo].[user_details] ADD  CONSTRAINT [DF__user__access__34C8D9D1]  DEFAULT ((1)) FOR [access]
GO

ALTER TABLE [dbo].[user_details] ADD  CONSTRAINT [DF__user__tutor__35BCFE0A]  DEFAULT ('0') FOR [tutor]
GO

ALTER TABLE [dbo].[user_details] ADD  CONSTRAINT [DF__user_deta__first__2B0A656D]  DEFAULT ((0)) FOR [firstlogin]
GO

ALTER TABLE [dbo].[user_details] ADD  CONSTRAINT [DF_user_details_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO


thank u :)

**Comment by jeremeguenther** [comment]
Those are the constraints, you already posted those above.  Is is the indexes and foreign keys that have not been posted.  However, it sounds like you are going in the right direction now to isolate which one is causing the issue.  I would recommend start by focusing on any indexes or foreign keys on columns that match the method names that are blowing up.

**Comment by ang-bain** [comment]
mmm..how strange they don't get include when you script the table..i'll keep plugging away..and shout if i don't have any joy..thanks for helping

**Comment by ang-bain** [comment]
Hi just a quick note to say i've got everything working again now...i took off all indexes and rebuilt without 2 offending ones that were generated by the sql tuning wizard..I'm not sure if moving to the new code base also helped..but thanks for helping :)

PS. I like this product and I would like to get involved..i'll start by keeping an eye out here for others needing help.  Speak soon Angela
