### ISSUE TITLE
DeepLoad true not traversing none null Properties

### ISSUE THREAD

**Issue by jeremeguenther** [netTiers/netTiers#470]
I have discovered that when using the DeepLoad methods with deep=true if one of the Properties has already been loaded or set to a non-null status, then the DeepLoad method will not traverse it to populate that sub objects Properties.

scenario:
Table1 with PK
Table2 with FK to Table1
Table3 with FK to Table2
Load Table2 and table3 entities
Assign Table3.Table2IdSource = Table2 entity
DeepLoad Table3 with deep=true, include entities Table2, Table1.
Result is that Table3.Table2IdSource.Table1IdSource is still null even after the deep load to populate it.

This seems like a bug to me.  I agree with the existing functionality that the existing object should not be re-loaded, however I would expect the existing object to be traversed so it's Properties can also be checked and loaded.

I believe that by using DeepLoad the developer should be able to ensure that all downstream relationships have been populated.

This should be a simple fix in the /DataAccessLayer/Bases/EntityProviderBaseCore.generated.cst file by moving the non-null recursive check outside of it's parent == null if statement check.

Is there any reason for the current functionality?  Or is it a bug that should be fixed as described?

**Comment by jeremeguenther** [comment]
@niemyjski  would you might double checking my logic on this?  I would like to fix the bug if you agree I am right about the issue.

**Comment by niemyjski** [comment]
I'm not sure, but that sounds like the right behavior. The thing is if you have table 2 and it's a parent of table3 then why would we ever go down further and check to see if it needs to be loaded as the parent would always be null or not explicitly loaded as you said don't include this root.

**Comment by jeremeguenther** [comment]
In my example I am saying to include table 2. It only breaks if that property was loaded prior to the deep load call.

So, if I had not explicitly assigned the table2idsource then the deep load would have correctly loaded both table2idsource and its child property table1idsource.

**Comment by niemyjski** [comment]
I get have it set to watching everything and I try to read them when they are in my inbox.  So basically you want to do a refresh an existing object with a deep load but the immediate child is populated but you want to populate the grand children?  I'm fine with proceeding with your fix.

**Comment by jeremeguenther** [comment]
New deep load features resolved this issue.
