### ISSUE TITLE
DeepLoad Regarding DeepLoad And Microsoft Azure Cloud!

### ISSUE THREAD

**Issue by PrakashMohan2000** [netTiers/netTiers#472]

**Comment by jeremeguenther** [comment]
I think more information is going to be required.
Have you tried other data access calls?  Is it just the deep load?  Have you tried different combinations of deep load, which combination is causing the time lag?
What is the specific deepload call that you believe to be the issue?

All deep load is is a bunch of recursive calls to the normal get methods.  Generally if there is a speed issue it is because deep load is being used incorrectly.  It is not a very efficient way to load data, so if a lot of data is being requested it will take a long time.

**Comment by jeremeguenther** [comment]
That is a very confusing list of data, but if I am interpreting it correctly:

OnPrem to OnPrem (two computers close to each other) is fast at less than 2 seconds.

OnPrem to Cloud (two computers very far apart) are slow taking more than a minute.

Cloud to Cloud (two computers close to each other) are fast at less than 2 seconds.

Makes perfect sense to me.  What is the issue?

**Comment by PrakashMohan2000** [comment]
Thank you for your response. We are pulling around 300 rows in this test method. It seems to be working fine till the first 50 rows and after that it starts slowing down. We may have to refactor our code for the cloud but just wanted to see if there was any alternative with out changing our code. Unfortunately we have used that deep load feature in a lot of places so may have to spend some time to refactor. Thank you again for your time and I appreciate any help if possible.

**Comment by jeremeguenther** [comment]
Deep loading an entire list of data like that seems like a pretty bad idea.  However, if the first 50 rows are working quickly then perhaps it has to do with the data you are loading.

I would suggest you step through the code while it is executing, and identify a few records that are fast, and a few records that are very slow.  Then compare the records and see what it different.  Perhaps you are loading a varchar(max) field, and it is empty or small on fast records, while it has entire documents for slow records.

**Comment by niemyjski** [comment]
I'd also make sure you have a big enough db size on azure. Deepload could be consuming more compute units

**Comment by PrakashMohan2000** [comment]
Blake,   Our database is around 33 GB in size. The disk has around 5- 10 GB additional space. Microsoft & Cisco are taking a look at it to see if it is a networking issue on their end will keep you posted and thank you very much for your response. The issue seems to happen when the traffic is from on-premise accessing the Microsoft Azure cloud database.
ThanksPrakash Mohan
    On Monday, January 14, 2019, 9:12:00 AM EST, Blake Niemyjski <notifications@github.com> wrote:  
 
 
I'd also make sure you have a big enough db size on azure. Deepload could be consuming more compute units
