### ISSUE TITLE
New to NetTiers and having difficulty with custom properties

### ISSUE THREAD

**Issue by jasona22** [netTiers/netTiers#473]
Feeling really dumb asking what I expect is exceptionally simple, but the answer is eluding me.  I have a parent child relationship.  The parent needs a custom property that is calculated based on some values in the children.  Say a customers list with open order count.  Typically I wouldn't store Open Order count on in the customer table.  So I want to add a custom property (found where I think I should do that in the Entites <objectname.cs> file.  Then I need to write a custom stored proc to do my calculation and return the value.  Easy enough.  However, I am not seeing where to wire that custom property to the custom result.  

I was under the impression when you created a custom stored proc, the result was returned in the provider or something.  I searched the google and oddly I've not found anything regarding custom properties and nettiers.  So clearly this is really easy and I am just not seeing it.

Thanks in advance for your help.

Jason

**Comment by jeremeguenther** [comment]
Custom sproc, with the correct naming convention generate methods in nettiers, they do not get wired up to properties.

The file you added your new property to allows you to create custom logic on top of nettiers, nettiers does not know anything about what you put in there.

There are several methods for achieving what you want.

Create a field in the database for the calculated value, then manually update it before each object save, possibly using a custom save method.

Create a field in the database, then use a database trigger to keep the value updated.

Add the property the way you have done, then create a custom get method to populate it. I'm not sure if nettiers has a load event you could hook for this, I would think it might.

Or have your property calculate itself on the fly inside the getter, you could create a private attribute to store the value in if you only wanted it to be calculated once.

I would either choose this last method or the database trigger depending on my needs.

**Comment by jasona22** [comment]
I appreciate your response.  I do not think adding a field in the database
is an option.  I am also trying to create something pseudo generic in that
it is an easy pattern to repeat or re-implement.

My thought was to create a "getter" function on the entity (myObject.cs)
and have a private mapper method there too.  However, it appears the
datarepository isn't easily accessible on the entity itself.  I really do
not want to do all this work in the UI.  It does not seem the right
location.  Is there a way to call the datarepository for getting my custom
results?  I got the custom stored proc to generate correctly.  And in the
UI I can call it.  I almost feel like  there needs to be a factory layer in
here somewhere that I can build objects; abstracting them away from the
UI.  For me, the UI should get its object and not care whether it is custom
or not.  It just receives an object it can act upon.

Jason

**Comment by jeremeguenther** [comment]
What is wrong with the last option then?

"have your property calculate itself on the fly inside the getter, you could create a private attribute to store the value in if you only wanted it to be calculated once"

If you want to call the custom sproc inside the getter you can. Just instantiate the service (or factory I think, I use service) object and call the custom sprocs method that got generated.
