### ISSUE TITLE
ANSI_NULLS in new versions of SQL

### ISSUE THREAD

**Issue by gregpakes** [netTiers/netTiers#480]
https://github.com/netTiers/netTiers/blob/bc8dcedb5aec8aecfeb45cb2aa23f9a63bae675e/Source/DataAccessLayer.SqlClient/StoredProceduresXml.cst#L612

According to https://docs.microsoft.com/en-us/sql/t-sql/statements/set-ansi-nulls-transact-sql?view=sql-server-ver15, setting ANSI_NULLS to OFF in future versions of SQL will cause errors.

Is there any thought around removing these from the netTiers codebase?

**Comment by gregpakes** [comment]
I see this has been dealt with here:

https://github.com/netTiers/netTiers/issues/384

Was the above missed? Or am I missing something?

**Comment by jeremeguenther** [comment]
It looks like that does not follow the pattern the other sprocs are using, and was missed.  I'll have to dig in a bit more.

**Comment by jeremeguenther** [comment]
I have removed those lines locally and bring that sproc in line with the other templates.  I'll run it through my testing systems before submitting a pull request for it.

**Comment by jeremeguenther** [comment]
This has been resolved in pr #481
