### ISSUE TITLE
High memory usage due to ValidationRules

### ISSUE THREAD

**Issue by gregpakes** [netTiers/netTiers#483]
We have a scenario where we have a rather large table (lots of columns).  We have noticed that the memory overhead of selecting from this table is extremely large.

This is due to the Validation Rules engine.

I am planning to look into refactoring the rules engine to be more efficient about how it stores the common rules against each entity. I don’t think needs to store copies against each entity of the same rules.

I don’t want to do this work if it won’t be accepted.

Is it worth me looking into?

**Comment by jeremeguenther** [comment]
That sounds like a logical improvement to me.

As long as you are only talking about rules added at compile time.  It would still need to support adding rules directly on the object at run-time for those people who do that.  A nice feature might be to include a hook that allows run-time code to insert rules either globally for the object type or at the instance level.

I've actually been testing out a small upgrade that creates generic hooks for custom validation at the instance level.  Hopefully i'll get that code checked in soon.

**Comment by gregpakes** [comment]
Yeh - I already planned for the custom rules.

Does your generic hook upgrade solve the memory issue?

**Comment by jeremeguenther** [comment]
No, it simply makes things more flexible at run time.

**Comment by gregpakes** [comment]
I have submitted a PR for this.

As I have outlined in the PR, there are a few areas that are fairly rough and ready and I am looking for feedback on them.
