### ISSUE TITLE
Question: Is there any way to specify which schemas to target?

### ISSUE THREAD

**Issue by rebeccapowell** [netTiers/netTiers#487]
We have a few different schemas in our source database, but I only want to generate for [dbo] objects. IS that possible without having to list all of the objects indivdually?

**Comment by jeremeguenther** [comment]
No, that is not currently possible with nettiers.
However, with a few hours work you could add the feature to the main template.

**Comment by rebeccapowell** [comment]
Ok thank you. My other option is to create a specific user that only has access to that specific schema and use SQL permissions to restrict the NetTiers user access from those database objects I don't want them to see.
