### ISSUE TITLE
Generating Template Methods For GetByID Not The Same MSSQL2014 vs MSSQL2019

### ISSUE THREAD

**Issue by moto-geek** [netTiers/netTiers#497]
I recently moved our database from MSSQL 2014 to MSSQL 2019 in our development and it broke all our DAL object references specifically all the GetByID methods.  As reference, I'm using CodeSmith 7.1 with netTiers. 

I try few things.. I ran the template against an old nettiers from 2006 and against the latest 2.3.2 with the same outcome. 

When I run it against MSSQL 2014 schema, I get the correct method to retrieve a record by the primary key id in a call to the method.

Examples Below:  

**Against MSSQL 2014 the {tablename}providerbasecore.generated.cs** in the Data Access Layer (DAL) generated project.

`public Users GetById(System.Int32 id)`

**But against MSSQL 2019 the {tablename}providerbasecore.generated.cs in the Data Access Layer (DAL) generated project. it's putting in collection reference when it can only return one record for the primary key id. This broke all our references**

`public exampleDB.BLL.TList<Users> GetById(System.Int32 id)`

Does anyone know how to fix this.. I tried setting the compatibility level in MSSQL2019 to make it 2014 and that did not work. I also removed my indexes to see if this was causing problem with no result. The only common denominator that changed was the version MSSQL Server of which the database is read from for generating the code from the template and data source.

**Comment by jeremeguenther** [comment]
I use SQL 2019 daily, so I know nettiers works with it.
Your symptoms indicate that the tables no longer have a unique constraint on the PK column.  Have you verified that Is Unique is set for your primary key index?

**Comment by moto-geek** [comment]
> I use SQL 2019 daily, so I know nettiers works with it. Your symptoms indicate that the tables no longer have a unique constraint on the PK column. Have you verified that Is Unique is set for your primary key index? 

I just double check and the PK in indexes property is "Unique, **Non-Clustered**"  Would non clustered versus clustered matter? Maybe this is it..

**Comment by moto-geek** [comment]
> I use SQL 2019 daily, so I know nettiers works with it. Your symptoms indicate that the tables no longer have a unique constraint on the PK column. Have you verified that Is Unique is set for your primary key index?

Appreciate the suggestion, but this was not it and PK is set to unique. A little more background. I generated the SQL Schema create script for the entire SQL2019 instance of my database and then built the database using the create script in my SQL2014 instance and it created the CORRECT version of NetTiers methods allowing unique GetByID without the Tlist reference in front of methods like I mentioned above. So this is why I suspect something is different in 2014 and 2019 leaving me perplexed.

**Comment by moto-geek** [comment]
Well I'm going to close this issue, but make a note for others..

netTiers was also reading my "_dta_%" generated non clustered indexes and this caused it to not see the unique. I dropped all the _dta_% prefixed indexes and then it resolved the problem. The below screenshot is before I removed the dta indexes. What queue me to look further is it was saying in the intellisense it was using a dta and not my PK index record.  

Before removal of _dta
![image](https://github.com/netTiers/netTiers/assets/7527202/ee89c445-7935-47f2-93c0-604411ed2f43)

After
![image](https://github.com/netTiers/netTiers/assets/7527202/6223d8d6-4962-4007-b022-720d131ef99a)

**Comment by moto-geek** [comment]
See above..  was not a SQL DB version issue more of a cleanup the database of extra indexes that through off the generation. Whenn I restored a production database, it was riddle with these causing this unexpected symptom

**Comment by jeremeguenther** [comment]
Nice find! I've had issues with tuning indexes as well, particularly when a tuning index ends up with the same columns as another index and duplicate method signatures get generated. 

I haven't seen it cause your issue, but it is good to know for the future.
