### ISSUE TITLE
Changing database.GetStoredProcCommand to StoredProcedureProvider.GetCommandWrapper crashes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [netTiers/netTiers#96]
```
What steps will reproduce the problem?
1. I have a stored procedure that works with v2.2.0.711 and doesn't with
.netTiers v2.3.0.b1
2. I have selected the same options in both
3. Debugging the autogenerated stored procedure code, I've seen that one
code-line has changed: 
(v2.2.0.711)
DbCommand commandWrapper =
database.GetStoredProcCommand("dbo._H_Numeradores_IncrementarNumerador");

(v2.3.0.b1)
DbCommand commandWrapper =
StoredProcedureProvider.GetCommandWrapper(database,
"dbo._H_Numeradores_IncrementarNumerador", _useStoredProcedure);

What is the expected output? What do you see instead?
It's expected that works fine, but now I always get an sqlexception saying
that cannot use a RETURN instruction with return value in that context.

What version of .netTiers and CodeSmith are you using?
Nettiers:v2.3.0.b1
Codesmith: 4.1.2

Please use labels and text to provide additional information.

Testing the stored procedure in sql query works fine. Stored Procedure also
works If I debug it in VS 2008 (CLR debugging).
```

Original issue reported on code.google.com by `alec...@gmail.com` on 2 Sep 2008 at 8:33

**Comment by benpowell** [comment]
For anyone else coming across this, we had a scenario whereby we were using dynamic SQL, once for the query and once to get a count that was done in a second dynamic EXEC, which then populated an OUTPUT param. The Codesmith Schema Explorer believed that this was a multiple CommandResult scenario. This AllowCustomProcMultipleResults was exactly what we needed when we knew that we wanted a VList<VwCustom> to be returned.

Notably the name of this setting leads you to believe that the generated service will accept multiple results back, but that is not its purpose. A better name would be:

- IgnoreCustomProcMultipleResultsAndForceTListOrVListRegardless

**Comment by niemyjski** [comment]
@benpowell thanks for the clarification.
